-- Seed game images for all 50 games
-- Maps 50 games to 22 available images with smart name matching and cycling

UPDATE Games SET ImageUrl = '/images/games/Red_Dead_Redemption_2.jpg' WHERE GameName = 'Red Dead Redemption 2';
UPDATE Games SET ImageUrl = '/images/games/Call_of_Duty_Modern_Warfare_II.jpg' WHERE GameName = 'VALORANT';
UPDATE Games SET ImageUrl = '/images/games/The_Last_of_Us_Part_II.jpg' WHERE GameName = 'The Last of Us Part II';
UPDATE Games SET ImageUrl = '/images/games/FIFA_23.jpg' WHERE GameName = 'FIFA 23';
UPDATE Games SET ImageUrl = '/images/games/Marvels_Spider-Man_Remastered.jpg' WHERE GameName = 'Marvel''s Spider-Man Remastered';
UPDATE Games SET ImageUrl = '/images/games/Call_of_Duty_Modern_Warfare_II.jpg' WHERE GameName = 'Call of Duty: Modern Warfare II';
UPDATE Games SET ImageUrl = '/images/games/Assassins_Creed_Valhalla.jpg' WHERE GameName = 'Assassin''s Creed Valhalla';
UPDATE Games SET ImageUrl = '/images/games/Horizon_Forbidden_West.jpg' WHERE GameName = 'Horizon Forbidden West';
UPDATE Games SET ImageUrl = '/images/games/Cyberpunk_2077.jpg' WHERE GameName = 'Fortnite';
UPDATE Games SET ImageUrl = '/images/games/Elden_Ring.jpg' WHERE GameName = 'Returnal';
UPDATE Games SET ImageUrl = '/images/games/Tekken_8.jpg' WHERE GameName = 'Gran Turismo 7';
UPDATE Games SET ImageUrl = '/images/games/Elden_Ring.jpg' WHERE GameName = 'Elden Ring';
UPDATE Games SET ImageUrl = '/images/games/Resident_Evil_4_Remake.jpg' WHERE GameName = 'Resident Evil 4 Remake';
UPDATE Games SET ImageUrl = '/images/games/Ghost_of_Tsushima.jpg' WHERE GameName = 'Ghost of Tsushima';
UPDATE Games SET ImageUrl = '/images/games/God_of_War_Ragnarok.jpg' WHERE GameName = 'God of War Ragnarök';
UPDATE Games SET ImageUrl = '/images/games/Cyberpunk_2077.jpg' WHERE GameName = 'Cyberpunk 2077';
UPDATE Games SET ImageUrl = '/images/games/Persona_5_Royal.jpg' WHERE GameName = 'Minecraft';
UPDATE Games SET ImageUrl = '/images/games/Marvels_Spider-Man_Remastered.jpg' WHERE GameName = 'Ratchet & Clank: Rift Apart';
UPDATE Games SET ImageUrl = '/images/games/Alan_Wake_2.jpg' WHERE GameName = 'Apex Legends';
UPDATE Games SET ImageUrl = '/images/games/Red_Dead_Redemption_2.jpg' WHERE GameName = 'Grand Theft Auto V';
UPDATE Games SET ImageUrl = '/images/games/Baldurs_Gate_3.jpg' WHERE GameName = 'Hogwarts Legacy';
UPDATE Games SET ImageUrl = '/images/games/The_Witcher_3_Wild_Hunt.jpg' WHERE GameName = 'The Witcher 3: Wild Hunt';
UPDATE Games SET ImageUrl = '/images/games/Starfield.jpg' WHERE GameName = 'Final Fantasy XVI';
UPDATE Games SET ImageUrl = '/images/games/Baldurs_Gate_3.jpg' WHERE GameName = 'Starfield';
UPDATE Games SET ImageUrl = '/images/games/Baldurs_Gate_3.jpg' WHERE GameName = 'Baldur''s Gate 3';
UPDATE Games SET ImageUrl = '/images/games/Black_Myth_Wukong.jpg' WHERE GameName = 'Palworld';
UPDATE Games SET ImageUrl = '/images/games/Alan_Wake_2.jpg' WHERE GameName = 'Helldivers 2';
UPDATE Games SET ImageUrl = '/images/games/Dragons_Dogma_2.jpg' WHERE GameName = 'Dragon Age: The Veilguard';
UPDATE Games SET ImageUrl = '/images/games/Tekken_8.jpg' WHERE GameName = 'Tekken 8';
UPDATE Games SET ImageUrl = '/images/games/Persona_5_Royal.jpg' WHERE GameName = 'Like a Dragon: Infinite Wealth';
UPDATE Games SET ImageUrl = '/images/games/Persona_5_Royal.jpg' WHERE GameName = 'Persona 5 Royal';
UPDATE Games SET ImageUrl = '/images/games/A_Plague_Tale_Requiem.jpg' WHERE GameName = 'Metaphor: ReFantazio';
UPDATE Games SET ImageUrl = '/images/games/Dragons_Dogma_2.jpg' WHERE GameName = 'Dragon''s Dogma 2';
UPDATE Games SET ImageUrl = '/images/games/Starfield.jpg' WHERE GameName = 'Final Fantasy VII Remake Intergrade';
UPDATE Games SET ImageUrl = '/images/games/Kena_Bridge_of_Spirits.jpg' WHERE GameName = 'Kingdom Come: Deliverance';
UPDATE Games SET ImageUrl = '/images/games/Star_Wars_Outlaws.jpg' WHERE GameName = 'Star Wars Outlaws';
UPDATE Games SET ImageUrl = '/images/games/Starfield.jpg' WHERE GameName = 'S.T.A.L.K.E.R. 2: Heart of Chornobyl';
UPDATE Games SET ImageUrl = '/images/games/Starfield.jpg' WHERE GameName = 'Indiana Jones and the Great Circle';
UPDATE Games SET ImageUrl = '/images/games/Black_Myth_Wukong.jpg' WHERE GameName = 'Black Myth: Wukong';
UPDATE Games SET ImageUrl = '/images/games/Alan_Wake_2.jpg' WHERE GameName = 'Hellblade II: Senua''s Saga';
UPDATE Games SET ImageUrl = '/images/games/Alan_Wake_2.jpg' WHERE GameName = 'Alan Wake 2';
UPDATE Games SET ImageUrl = '/images/games/Star_Wars_Outlaws.jpg' WHERE GameName = 'Star Wars Jedi: Survivor';
UPDATE Games SET ImageUrl = '/images/games/Kena_Bridge_of_Spirits.jpg' WHERE GameName = 'Kena: Bridge of Spirits';
UPDATE Games SET ImageUrl = '/images/games/A_Plague_Tale_Requiem.jpg' WHERE GameName = 'A Plague Tale: Requiem';
UPDATE Games SET ImageUrl = '/images/games/Resident_Evil_4_Remake.jpg' WHERE GameName = 'Dead Space Remake';
UPDATE Games SET ImageUrl = '/images/games/Alan_Wake_2.jpg' WHERE GameName = 'The Callisto Protocol';
UPDATE Games SET ImageUrl = '/images/games/A_Plague_Tale_Requiem.jpg' WHERE GameName = 'Deathloop';
UPDATE Games SET ImageUrl = '/images/games/Alan_Wake_2.jpg' WHERE GameName = 'Ghostwire: Tokyo';
UPDATE Games SET ImageUrl = '/images/games/Tekken_8.jpg' WHERE GameName = 'Sifu';
UPDATE Games SET ImageUrl = '/images/games/Cyberpunk_2077.jpg' WHERE GameName = 'Final Fantasy XV';
