// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSstore.Data;

#nullable disable

namespace PSstore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260115063844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PSstore.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AdminPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            AdminEmail = "admin@psstore.com",
                            AdminPassword = "Admin@123",
                            CreatedAt = new DateTime(2026, 1, 15, 6, 38, 44, 66, DateTimeKind.Utc).AddTicks(2515)
                        });
                });

            modelBuilder.Entity("PSstore.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("PSstore.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtMoment")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("GameId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("PSstore.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Adventure"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "RPG"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Racing"
                        });
                });

            modelBuilder.Entity("PSstore.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<bool>("FreeToPlay")
                        .HasColumnType("bit");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsMultiplayer")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            FreeToPlay = false,
                            GameName = "God of War",
                            IsMultiplayer = false,
                            Price = 49.99m,
                            PublishedBy = "Sony",
                            ReleaseDate = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameId = 2,
                            FreeToPlay = false,
                            GameName = "Spider-Man",
                            IsMultiplayer = false,
                            Price = 59.99m,
                            PublishedBy = "Sony",
                            ReleaseDate = new DateTime(2018, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameId = 3,
                            FreeToPlay = true,
                            GameName = "Fortnite",
                            IsMultiplayer = true,
                            Price = 0m,
                            PublishedBy = "Epic Games",
                            ReleaseDate = new DateTime(2017, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameId = 4,
                            FreeToPlay = false,
                            GameName = "Gran Turismo 7",
                            IsMultiplayer = true,
                            Price = 69.99m,
                            PublishedBy = "Sony",
                            ReleaseDate = new DateTime(2022, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PSstore.Models.GameCategory", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("GameCategories");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            GameId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            GameId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            GameId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            GameId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            GameId = 4,
                            CategoryId = 5
                        });
                });

            modelBuilder.Entity("PSstore.Models.GameSubscription", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "SubscriptionId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("GameSubscriptions");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            SubscriptionId = 2
                        },
                        new
                        {
                            GameId = 1,
                            SubscriptionId = 3
                        },
                        new
                        {
                            GameId = 2,
                            SubscriptionId = 3
                        });
                });

            modelBuilder.Entity("PSstore.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegionTimezone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RegionId");

                    b.HasIndex("RegionCode")
                        .IsUnique();

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            Currency = "USD",
                            RegionCode = "US",
                            RegionName = "United States",
                            RegionTimezone = "America/New_York"
                        },
                        new
                        {
                            RegionId = 2,
                            Currency = "EUR",
                            RegionCode = "EU",
                            RegionName = "Europe",
                            RegionTimezone = "Europe/London"
                        },
                        new
                        {
                            RegionId = 3,
                            Currency = "JPY",
                            RegionCode = "JP",
                            RegionName = "Japan",
                            RegionTimezone = "Asia/Tokyo"
                        },
                        new
                        {
                            RegionId = 4,
                            Currency = "INR",
                            RegionCode = "IN",
                            RegionName = "India",
                            RegionTimezone = "Asia/Kolkata"
                        });
                });

            modelBuilder.Entity("PSstore.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubscriptionId");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            SubscriptionId = 1,
                            SubscriptionType = "PlayStation Plus Essential"
                        },
                        new
                        {
                            SubscriptionId = 2,
                            SubscriptionType = "PlayStation Plus Extra"
                        },
                        new
                        {
                            SubscriptionId = 3,
                            SubscriptionType = "PlayStation Plus Premium"
                        });
                });

            modelBuilder.Entity("PSstore.Models.SubscriptionPlanRegion", b =>
                {
                    b.Property<int>("SubscriptionPlanRegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionPlanRegionId"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionPlanRegionId");

                    b.HasIndex("RegionId");

                    b.HasIndex("SubscriptionId", "RegionId")
                        .IsUnique();

                    b.ToTable("SubscriptionPlanRegions");

                    b.HasData(
                        new
                        {
                            SubscriptionPlanRegionId = 1,
                            Currency = "USD",
                            Price = 9.99m,
                            RegionId = 1,
                            SubscriptionId = 1
                        },
                        new
                        {
                            SubscriptionPlanRegionId = 2,
                            Currency = "EUR",
                            Price = 8.99m,
                            RegionId = 2,
                            SubscriptionId = 1
                        },
                        new
                        {
                            SubscriptionPlanRegionId = 3,
                            Currency = "USD",
                            Price = 14.99m,
                            RegionId = 1,
                            SubscriptionId = 2
                        },
                        new
                        {
                            SubscriptionPlanRegionId = 4,
                            Currency = "EUR",
                            Price = 13.99m,
                            RegionId = 2,
                            SubscriptionId = 2
                        },
                        new
                        {
                            SubscriptionPlanRegionId = 5,
                            Currency = "USD",
                            Price = 17.99m,
                            RegionId = 1,
                            SubscriptionId = 3
                        });
                });

            modelBuilder.Entity("PSstore.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubscriptionStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Age = 28,
                            CreatedAt = new DateTime(2026, 1, 15, 6, 38, 44, 66, DateTimeKind.Utc).AddTicks(2535),
                            UserEmail = "john@example.com",
                            UserName = "john_doe",
                            UserPassword = "Pass@123"
                        },
                        new
                        {
                            UserId = 2,
                            Age = 25,
                            CreatedAt = new DateTime(2026, 1, 15, 6, 38, 44, 66, DateTimeKind.Utc).AddTicks(2538),
                            SubscriptionStatus = "Active",
                            UserEmail = "jane@example.com",
                            UserName = "jane_smith",
                            UserPassword = "Pass@456"
                        });
                });

            modelBuilder.Entity("PSstore.Models.UserPurchaseGame", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseId"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PurchaseId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPurchaseGames");
                });

            modelBuilder.Entity("PSstore.Models.UserSubscriptionPlan", b =>
                {
                    b.Property<int>("UserSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSubscriptionId"));

                    b.Property<DateTime>("PlanEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlanStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionPlanRegionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserSubscriptionId");

                    b.HasIndex("SubscriptionPlanRegionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscriptionPlans");
                });

            modelBuilder.Entity("PSstore.Models.UsersRegion", b =>
                {
                    b.Property<int>("UserRegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRegionId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRegionId");

                    b.HasIndex("RegionId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersRegions");

                    b.HasData(
                        new
                        {
                            UserRegionId = 1,
                            IsActive = true,
                            RegionId = 1,
                            StartDate = new DateTime(2026, 1, 15, 6, 38, 44, 66, DateTimeKind.Utc).AddTicks(2560),
                            UserId = 1
                        },
                        new
                        {
                            UserRegionId = 2,
                            IsActive = true,
                            RegionId = 2,
                            StartDate = new DateTime(2026, 1, 15, 6, 38, 44, 66, DateTimeKind.Utc).AddTicks(2561),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("PSstore.Models.Cart", b =>
                {
                    b.HasOne("PSstore.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PSstore.Models.CartItem", b =>
                {
                    b.HasOne("PSstore.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSstore.Models.Game", "Game")
                        .WithMany("CartItems")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("PSstore.Models.GameCategory", b =>
                {
                    b.HasOne("PSstore.Models.Category", "Category")
                        .WithMany("GameCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSstore.Models.Game", "Game")
                        .WithMany("GameCategories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("PSstore.Models.GameSubscription", b =>
                {
                    b.HasOne("PSstore.Models.Game", "Game")
                        .WithMany("GameSubscriptions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSstore.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("GameSubscriptions")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("PSstore.Models.SubscriptionPlanRegion", b =>
                {
                    b.HasOne("PSstore.Models.Region", "Region")
                        .WithMany("SubscriptionPlanRegions")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSstore.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("SubscriptionPlanRegions")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("PSstore.Models.UserPurchaseGame", b =>
                {
                    b.HasOne("PSstore.Models.Game", "Game")
                        .WithMany("UserPurchases")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSstore.Models.User", "User")
                        .WithMany("UserPurchasedGames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PSstore.Models.UserSubscriptionPlan", b =>
                {
                    b.HasOne("PSstore.Models.SubscriptionPlanRegion", "SubscriptionPlanRegion")
                        .WithMany("UserSubscriptionPlans")
                        .HasForeignKey("SubscriptionPlanRegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSstore.Models.User", "User")
                        .WithMany("UserSubscriptionPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlanRegion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PSstore.Models.UsersRegion", b =>
                {
                    b.HasOne("PSstore.Models.Region", "Region")
                        .WithMany("UsersRegions")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSstore.Models.User", "User")
                        .WithMany("UsersRegions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PSstore.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("PSstore.Models.Category", b =>
                {
                    b.Navigation("GameCategories");
                });

            modelBuilder.Entity("PSstore.Models.Game", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("GameCategories");

                    b.Navigation("GameSubscriptions");

                    b.Navigation("UserPurchases");
                });

            modelBuilder.Entity("PSstore.Models.Region", b =>
                {
                    b.Navigation("SubscriptionPlanRegions");

                    b.Navigation("UsersRegions");
                });

            modelBuilder.Entity("PSstore.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("GameSubscriptions");

                    b.Navigation("SubscriptionPlanRegions");
                });

            modelBuilder.Entity("PSstore.Models.SubscriptionPlanRegion", b =>
                {
                    b.Navigation("UserSubscriptionPlans");
                });

            modelBuilder.Entity("PSstore.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("UserPurchasedGames");

                    b.Navigation("UserSubscriptionPlans");

                    b.Navigation("UsersRegions");
                });
#pragma warning restore 612, 618
        }
    }
}
